language: node_js
services:
  - mongodb
  - redis-server
node_js:
  - v6
  - v5
  - v4
  - '0.12'
  - '0.10'
before_script:
  - mongo nodeforum --eval 'db.addUser("test", "test");'

env:
- NWF_MONGO_DB=mongodb:test@test//127.0.0.1/nodeforum
